import React,{useEffect,useMemo,useState}from'react';
import{Bell,ChevronDown,Gift,Home,Menu,Play,PlayCircle,Trophy,UserRound,X,CheckCircle2,Clock3,LoaderCircle,ShieldCheck,Plus,Users,Flame,WalletCards,Target,Medal,ArrowUpRight,Star,LockKeyhole,Phone,Mail,Send,BadgeCheck,CalendarDays,Info,Shield,ClipboardCheck,ListChecks,HelpCircle,Headphones,RotateCcw,Coins,Rocket,PartyPopper,ShieldAlert,UserRoundCheck}from'lucide-react';
import{ADS,LEADERBOARD,GOAL,GIFT_REWARDS}from'./data';
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
export default function App(){
 const[page,setPage]=useState('watch'),[open,setOpen]=useState(false),[watched,setWatched]=useState(load('watched',[])),[today,setToday]=useState(load('today',0)),[life,setLife]=useState(load('life',0)),[activity,setActivity]=useState(load('activity',[])),[giftEntry,setGiftEntry]=useState(load('giftEntry',null)),[selected,setSelected]=useState(null),[status,setStatus]=useState('idle'),[left,setLeft]=useState(0),[progress,setProgress]=useState(0);
 useEffect(()=>{save('watched',watched);save('today',today);save('life',life);save('activity',activity);save('giftEntry',giftEntry)},[watched,today,life,activity]);
 const available=useMemo(()=>ADS.filter(a=>!watched.includes(a.id)),[watched]);
 const balance=2450+life;
 const watch=ad=>{setSelected(ad);setStatus('loading');setLeft(ad.duration);setProgress(0);setTimeout(()=>{setStatus('watching');let n=ad.duration;const t=setInterval(()=>{n--;setLeft(n);setProgress((ad.duration-n)/ad.duration*100);if(n<=0){clearInterval(t);setProgress(100);setStatus('completed');setWatched(x=>x.includes(ad.id)?x:[...x,ad.id]);setToday(x=>x+1);setLife(x=>x+ad.reward);setActivity(x=>[{id:Date.now(),reward:ad.reward,brand:ad.brand,time:'just now'},...x])}},1000)},650)};
 const close=()=>{setSelected(null);setStatus('idle');setLeft(0)};
 const reset=()=>{localStorage.clear();location.reload()};
 const nav=p=>{setPage(p);setOpen(false)};
 return <div className="shell">
  <aside className={open?'side open':'side'}><div className="brand"><div className="logo-mark">V</div><div><strong>VELOOP</strong><small>Rewards & Giveaways</small></div><button className="close" onClick={()=>setOpen(false)}><X/></button></div>
   <nav><button className={page==='home'?'active':''} onClick={()=>nav('home')}><Home/>Dashboard</button><button className={page==='watch'?'active':''} onClick={()=>nav('watch')}><PlayCircle/>Watch & Earn</button><button className={page==='rewards'?'active':''} onClick={()=>nav('rewards')}><Gift/>Rewards</button><button className={page==='leaderboard'?'active':''} onClick={()=>nav('leaderboard')}><Trophy/>Leaderboard</button><button className={page==='profile'?'active':''} onClick={()=>nav('profile')}><UserRound/>Profile</button><button className={page==='how'?'active':''} onClick={()=>nav('how')}><ListChecks/>How It Works</button><button className={page==='safety'?'active':''} onClick={()=>nav('safety')}><Shield/>Eligibility & Safety</button></nav>
   <div className="side-art"><div className="headphone"><Headphones/></div><div className="script">Watch<br/>Earn<br/>Win</div><b>Your Time<br/><span>=</span><br/>Real Rewards</b></div>
  </aside>
  <main><header><div className="head-left"><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div className="welcome"><div className="avatar-group"><Users/></div><div><strong>Hello, Hansa Prajapat</strong><small>Keep watching, keep earning!</small></div></div></div><div className="head-right"><Bell className="bell"/><div className="balance"><span>VE</span><b>{balance.toLocaleString()}</b><Plus/></div><div className="profile-avatar"><UserRound/></div><ChevronDown/></div></header>
   {page==='watch'&&<WatchPage {...{watched,today,life,balance,available,activity,watch,setPage}}/>}
   {page==='leaderboard'&&<LeaderboardPage balance={balance} today={today} watched={watched} setPage={setPage}/>} 
   {page==='rewards'&&<RewardsPage balance={balance} setPage={setPage}/>} 
   {page==='home'&&<HomePage balance={balance} watched={watched} today={today} setPage={setPage}/>} 
   {page==='how'&&<HowItWorksPage setPage={setPage}/>}
   {page==='safety'&&<SafetyPage setPage={setPage}/>}
   {page==='profile'&&<ProfilePage balance={balance} watched={watched} today={today} giftEntry={giftEntry} setGiftEntry={setGiftEntry} setPage={setPage}/>} 
   <footer>© 2025 Veloop Rewards & Giveaways <span>|</span> Watch <span>•</span> Earn <span>•</span> Win <small>Demo rewards & points experience</small></footer><button className="reset-fab" title="Reset demo" onClick={reset}><RotateCcw/></button>
  </main>
  {selected&&<div className="modal"><div className="watch-modal"><button className="modal-x" onClick={close}><X/></button>{status==='loading'&&<div className="state"><LoaderCircle className="spin"/><h2>Loading advertisement…</h2><p>Preparing your reward session.</p></div>}{status==='watching'&&<div className="state"><div className="fake">{selected.icon}<b>{selected.brand}</b><small>SPONSORED PREVIEW</small></div><div className="timer"><span>Watching advertisement</span><b>{left}s</b></div><div className="bar"><i style={{width:progress+'%'}}/></div><p>Please keep this window open until the timer reaches zero.</p></div>}{status==='completed'&&<div className="state"><div className="success">✓</div><h2>Reward successful!</h2><p>You earned <b>+{selected.reward} VE</b> for completing {selected.brand}.</p><span className="note"><ShieldCheck/>Reward added to your balance</span><button className="continue" onClick={close}>Continue</button></div>}</div></div>}
 </div>
}
function WatchPage({watched,today,balance,available,activity,watch,setPage}){return <section className="page"><div className="hero"><div className="hero-copy"><span className="new-badge">NEW</span><h1>Watch & Earn</h1><h2>Turn your time into rewards!</h2><p>Watch short ads, complete the timer and<br/>get VE points instantly.</p><button className="hero-btn" onClick={()=>available[0]&&watch(available[0])}><Play fill="currentColor"/>Watch Now <Play fill="currentColor"/></button></div><div className="hero-visual"><div className="screen"><div><PlayCircle/></div></div><div className="coin c1">VE</div><div className="coin c2">VE</div><div className="coin c3">VE</div><div className="clock-ring"><Clock3/></div><span className="ad-tag">AD</span><i>Earn<br/>More<br/>VE ↗</i></div></div>
 <div className="content-grid"><div className="main-col"><div className="stats"><Stat icon={<Play/>} label="Ads Watched" value={`${watched.length} / 10`} progress={watched.length*10} hint={`${Math.max(0,10-watched.length)} more to complete today`}/><Stat cls="green" icon={<WalletCards/>} label="Today's Earnings" value={`+${today*15} VE`} hint="Keep building your points"/><Stat cls="pink" icon={<Flame/>} label="Daily Streak" value="3 Days" hint="Keep it up!"/><Stat cls="blue" icon={<WalletCards/>} label="Total Balance" value={`${balance.toLocaleString()} VE`} hint="Points in your demo wallet"/></div>
 <div className="earning-strip card"><div><Star/><b>Weekly leaderboard is live</b><span>Watch more ads, climb the ranks and unlock gift rewards.</span></div><button onClick={()=>setPage('leaderboard')}>View Leaderboard <ArrowUpRight/></button></div>
 <div className="ads-heading"><div><h2><PlayCircle/>Available Ads</h2><p>Watch ads, complete the timer and earn VE points.</p></div><span>{ADS.length} Unique Ads</span></div><div className="ads">{ADS.map((a,i)=><article className={watched.includes(a.id)?'ad card done':'ad card'} key={a.id}><div className={`ad-visual ${a.tone}`}><em>{i+1}</em><small><Clock3/> {a.duration}s</small><div className="ad-image">{a.icon}</div></div><div className="ad-body"><h3>{a.title}</h3><p><span className="coin-icon"><Coins/></span> +{a.reward} VE</p><button disabled={watched.includes(a.id)} onClick={()=>watch(a)}>{watched.includes(a.id)?<><CheckCircle2/>Watched</>:<><Play fill="currentColor"/>Watch Now</>}</button></div></article>)}</div></div>
 <aside className="right-col"><div className="bonus-card card"><div className="gift-art"><Gift/></div><div><h3>Daily Bonus</h3><p>Claim your daily bonus<br/>and get extra VE</p><button onClick={()=>setPage('rewards')}>Claim Now →</button></div></div><div className="side-card card"><div className="side-card-title"><h3><Target/>Daily Progress</h3><a onClick={()=>setPage('leaderboard')}>View All</a></div><div className="progress-line"><i style={{width:`${Math.min(100,watched.length*10)}%`}}/></div><div className="progress-num">{watched.length}/10</div><p className="motivation"><Rocket/> Great! You're almost there!</p></div><div className="side-card card activity"><div className="side-card-title"><h3><Clock3/>Recent Activity</h3></div>{(activity.length?activity:[{id:1,reward:20,time:'2 mins ago'},{id:2,reward:25,time:'15 mins ago'},{id:3,reward:15,time:'32 mins ago'}]).slice(0,4).map(x=><div className="activity-row" key={x.id}><CheckCircle2/><span>You earned <b>+{x.reward} VE</b></span><small>{x.time}</small></div>)}</div><div className="success-card"><div><Trophy/></div><h3>Win Gift Rewards</h3><p>Top players on the weekly leaderboard unlock <b>gift rewards</b>.</p><button onClick={()=>setPage('leaderboard')}>See Rankings</button></div></aside></div></section>}
function Stat({icon,label,value,progress,hint,cls=''}){return <div className={`stat card ${cls}`}><div className="stat-icon">{icon}</div><span>{label}</span><b>{value}</b>{progress!==undefined&&<i><u style={{width:`${progress}%`}}/></i>}<small>{hint}</small></div>}
function LeaderboardPage({balance,today,watched,setPage}){return <section className="page"><div className="leader-hero card"><div><span className="eyebrow">WEEKLY CHALLENGE</span><h1>Climb the Leaderboard</h1><p>Watch eligible ads, collect VE points and move up the weekly ranking.</p><div className="leader-actions"><button onClick={()=>setPage('watch')}><Play/> Watch Ads</button><button className="secondary" onClick={()=>setPage('rewards')}><Gift/> View Gifts</button></div></div><div className="trophy-orbit"><Trophy/></div></div><div className="prize-row">{GIFT_REWARDS.map(g=><div className="prize card" key={g.rank}><span>#{g.rank}</span><div>{g.icon}</div><b>{g.title}</b><small>{g.subtitle}</small></div>)}</div><div className="leader-grid"><div className="leader-table card"><div className="section-title"><h2><Trophy/> Weekly Rankings</h2><span>Resets every 7 days</span></div>{LEADERBOARD.map((p,i)=><div className={`rank-row ${i===0?'top':''}`} key={p.name}><div className="rank">{i+1}</div><div className="rank-avatar">{p.avatar}</div><div className="rank-name"><b>{p.name}</b><small>{p.ads} ads watched</small></div><strong>{p.points.toLocaleString()} VE</strong><span className={`rank-badge r${i+1}`}>{i===0?'1st':i===1?'2nd':i===2?'3rd':'Top player'}</span></div>)}</div><div className="my-rank card"><div className="section-title"><h2><Medal/> Your Rank</h2></div><div className="your-rank-number">#12</div><p>Keep watching to reach the top 10.</p><div className="mini-progress"><i style={{width:'68%'}}/></div><div className="rank-stats"><span><b>{today*15}</b><small>Today VE</small></span><span><b>{watched.length}</b><small>Ads watched</small></span><span><b>{balance}</b><small>Balance</small></span></div><button onClick={()=>setPage('watch')}>Earn More VE <ArrowUpRight/></button></div></div></section>}
function RewardsPage({balance,setPage}){return <section className="page"><div className="bonus-page card"><Gift/><span>REWARDS CENTER</span><h1>Turn points into achievements</h1><p>Build your VE balance through the demo Watch & Earn experience and unlock milestone gifts.</p></div><div className="reward-grid">{GIFT_REWARDS.map((g,i)=><div className="reward-box card" key={g.rank}><div className="reward-icon">{g.icon}</div><div><small>RANK #{g.rank}</small><h3>{g.title}</h3><p>{g.subtitle}</p><button onClick={()=>setPage('leaderboard')}>View leaderboard</button></div></div>)}</div><div className="wallet-banner card"><WalletCards/><div><span>Your demo VE balance</span><b>{balance.toLocaleString()} VE</b></div><LockKeyhole/><small>Points are for the project demo experience.</small></div></section>}
function HomePage({balance,watched,today,setPage}){return <section className="page"><div className="leader-hero card"><div><span className="eyebrow">YOUR DASHBOARD</span><h1>Everything in one place</h1><p>Track your ads, points, daily progress and weekly leaderboard position.</p><div className="leader-actions"><button onClick={()=>setPage('watch')}><Play/> Start Earning</button><button className="secondary" onClick={()=>setPage('leaderboard')}><Trophy/> Leaderboard</button></div></div><div className="dashboard-orbit">{balance.toLocaleString()}<small>VE BALANCE</small></div></div><div className="overview-grid"><div className="card overview"><PlayCircle/><span>Ads watched</span><b>{watched.length}</b></div><div className="card overview"><WalletCards/><span>Today's points</span><b>{today*15} VE</b></div><div className="card overview"><Trophy/><span>Weekly rank</span><b>#12</b></div><div className="card overview"><Gift/><span>Next gift</span><b>Top 10</b></div></div></section>}

function HowItWorksPage({setPage}){return <section className="page"><div className="info-hero card"><div><span className="eyebrow">HOW VELOOP WORKS</span><h1>Watch • Earn • Climb • Win</h1><p>A simple demo flow showing how users can move from watching eligible ads to earning points and competing for giveaway rewards.</p><button onClick={()=>setPage('watch')}><Play/> Start Demo</button></div><div className="info-orbit"><PlayCircle/><small>4 STEPS</small></div></div><div className="steps-grid">{[{n:'01',icon:<PlayCircle/>,title:'Watch an eligible ad',text:'Choose an available ad and complete the on-screen timer without skipping.'},{n:'02',icon:<WalletCards/>,title:'Receive VE points',text:'After completion, the demo adds the listed VE reward to your balance and activity.'},{n:'03',icon:<Trophy/>,title:'Climb the leaderboard',text:'Your points contribute to the demo weekly ranking so you can see your position.'},{n:'04',icon:<Gift/>,title:'Winner gift process',text:'If a real giveaway is offered, an eligible winner can submit a gift entry for fulfilment.'}].map(x=><div className="step-card card" key={x.n}><span>{x.n}</span><div className="step-icon">{x.icon}</div><h3>{x.title}</h3><p>{x.text}</p></div>)}</div><div className="process-note card"><Info/><div><b>Demo process</b><p>This project is a frontend demonstration. VE points, rankings and gift entries shown here are sample data unless connected to a real backend and verified reward provider.</p></div></div></section>}
function SafetyPage({setPage}){return <section className="page"><div className="info-hero safety-hero card"><div><span className="eyebrow">ELIGIBILITY & SAFETY</span><h1>Clear rules. Safer experience.</h1><p>Use the app as a project demo and follow the eligibility, privacy and reward rules shown before any real promotion is launched.</p><button onClick={()=>setPage('profile')}><UserRound/> View Profile</button></div><div className="safe-orbit"><ShieldCheck/><small>SAFE DEMO</small></div></div><div className="safety-grid"><div className="card safety-card"><h2><ClipboardCheck/> Eligibility</h2><ul><li><CheckCircle2/>For a real rewards or giveaway service, eligibility and age requirements must be clearly stated in its official terms.</li><li><CheckCircle2/>Only verified participants who meet the published promotion rules should be considered for real prizes.</li><li><CheckCircle2/>For this student/project demo, use sample data; do not treat demo points as guaranteed cash or prizes.</li></ul></div><div className="card safety-card"><h2><Shield/> App Safety</h2><ul><li><ShieldCheck/>Use HTTPS when deployed and keep account/payment information out of this frontend demo.</li><li><LockKeyhole/>The demo stores progress locally in the browser; clear local data if you want to reset the demo.</li><li><Info/>Never enter passwords, bank details, OTPs or other sensitive information into a demo form.</li></ul></div></div><div className="safe-checklist card"><div className="section-title"><h2><ListChecks/> Before using a real reward flow</h2><span>Recommended checklist</span></div><div className="check-grid"><span>✓ Read official terms</span><span>✓ Verify the organizer</span><span>✓ Check age eligibility</span><span>✓ Confirm prize details</span><span>✓ Protect personal information</span><span>✓ Keep proof of legitimate participation</span></div></div><div className="process-note card"><HelpCircle/><div><b>Important</b><p>“Safe” here means the demo follows basic frontend safety practices; no website can be guaranteed completely safe without reviewing its backend, hosting, dependencies, data handling and real-world operators.</p></div></div></section>}

function ProfilePage({balance,watched,today,giftEntry,setGiftEntry,setPage}){
 const[form,setForm]=useState({name:'Hansa Prajapat',phone:'',email:'',address:'',gift:'Grand Gift Box'});
 const submit=e=>{e.preventDefault();setGiftEntry({...form,status:'Pending verification',submittedAt:new Date().toLocaleDateString()})};
 return <section className="page"><div className="profile-card card"><div className="big-avatar"><UserRound/></div><div><span className="eyebrow">MEMBER PROFILE</span><h1>Hansa Prajapat</h1><p>VELOOP Rewards member · Demo account</p></div><div className="profile-balance"><small>Balance</small><b>{balance.toLocaleString()} VE</b></div></div><div className="profile-grid"><div className="card profile-stat"><Trophy/><b>#12</b><span>Weekly rank</span></div><div className="card profile-stat"><PlayCircle/><b>{watched.length}</b><span>Ads completed</span></div><div className="card profile-stat"><Flame/><b>3</b><span>Day streak</span></div></div><div className="profile-detail-grid"><div className="card profile-details"><div className="section-title"><h2><UserRound/> Profile Details</h2><span>Member since 2026</span></div><div className="detail-list"><div><Mail/><span>Email</span><b>Demo account</b></div><div><Phone/><span>Contact</span><b>Not added</b></div><div><Target/><span>Today's progress</span><b>{today}/10 ads</b></div><div><Trophy/><span>Leaderboard</span><b>Weekly #12</b></div></div><button className="wide-cta" onClick={()=>setPage('watch')}><Play/> Continue watching ads</button></div><div className="card gift-entry"><div className="section-title"><h2><Gift/> Winner Gift Entry</h2><span>Claim & delivery</span></div>{giftEntry?<div className="entry-success"><BadgeCheck/><h3>Gift entry created</h3><p><b>{giftEntry.name}</b> is registered for <b>{giftEntry.gift}</b>.</p><span><CalendarDays/> Submitted {giftEntry.submittedAt} · {giftEntry.status}</span><button onClick={()=>setGiftEntry(null)}>Create New Entry</button></div>:<form onSubmit={submit}><p className="entry-help">When a player wins a giveaway, create their entry here so the reward team can process the gift.</p><label>Winner name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><div className="form-two"><label>Contact number<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Demo contact" required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="winner@example.com" required/></label></div><label>Gift won<select value={form.gift} onChange={e=>setForm({...form,gift:e.target.value})}><option>Grand Gift Box</option><option>Premium Gift</option><option>Bonus Gift</option></select></label><label>Delivery address<textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Demo delivery address" required/></label><button className="submit-entry" type="submit"><Send/> Create Gift Entry</button></form>}</div></div></section>}
